### ISSUE TITLE
SELECT JOIN field with the same name not shown

### ISSUE THREAD

**Issue by UniBreakfast** [poreklo/vscode-mysql#4]
"SELECT * FROM table1 JOIN table2 ON table1.id=table2.user_id"

- in Result page there are all fields except for the fields from the table1 named as the fields from table2. Unless I explicitly rename them with AS

**Comment by poreklo** [comment]
I can do it like this.
![Code_n4RG7rw9og](https://user-images.githubusercontent.com/24385191/56054586-a22ba380-5d70-11e9-81d2-88c674b3fe40.png)
