### ISSUE TITLE
Escape database, table and column names

### ISSUE THREAD

**Issue by theking2** [poreklo/vscode-mysql#7]
./model/tableNode.ts#49 add ` to database and table names; 

`        const sql = `SELECT * FROM \`${this.database}\`.\`${this.table}\` LIMIT 1000;`;
`

**Comment by poreklo** [comment]
why?

**Comment by theking2** [comment]
Easy: it will allow queries with tables colomns and databases with extended
character sets or reserve words. See
https://mariadb.com/kb/en/identifier-names/

Nothing is hurt but a lot is gained quoting table, column and database names

Op di 14 jan. 2020 17:51 schreef Yury Bukin <notifications@github.com>:

**Comment by poreklo** [comment]
commit 76aafa8ce08fd1799b365f4d9be67de0e6f6a9aa
